# Stubs for praw.models.reddit.message (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...const import API_PATH
from .base import RedditBase
from .mixins import InboxableMixin, ReplyableMixin
from .redditor import Redditor
from .subreddit import Subreddit
from typing import Any

class Message(RedditBase, InboxableMixin, ReplyableMixin):
    STR_FIELD: str = ...
    @classmethod
    def parse(cls, data: Any, reddit: Any): ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def delete(self) -> None: ...

class SubredditMessage(Message):
    def mute(self, _unmute: bool = ...) -> None: ...
    def unmute(self) -> None: ...
