# Stubs for praw.models.list.redditor (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import BaseList

class RedditorList(BaseList):
    CHILD_ATTRIBUTE: str = ...
