# Stubs for praw.models.list.trophy (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import BaseList

class TrophyList(BaseList):
    CHILD_ATTRIBUTE: str = ...
