# Stubs for praw.models.listing.mixins.gilded (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ....const import urljoin
from ...base import PRAWBase
from ..generator import ListingGenerator
from typing import Any

class GildedListingMixin(PRAWBase):
    def gilded(self, **generator_kwargs: Any): ...
