# Stubs for praw.models.listing.mixins.rising (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ....const import urljoin
from ...base import PRAWBase
from ..generator import ListingGenerator
from typing import Any

class RisingListingMixin(PRAWBase):
    def random_rising(self, **generator_kwargs: Any): ...
    def rising(self, **generator_kwargs: Any): ...
