# Stubs for praw.models.listing.mixins.subreddit (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ....const import urljoin
from ...base import PRAWBase
from ..generator import ListingGenerator
from .base import BaseListingMixin
from .gilded import GildedListingMixin
from .rising import RisingListingMixin
from typing import Any

class SubredditListingMixin(BaseListingMixin, GildedListingMixin, RisingListingMixin):
    @property
    def comments(self): ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...

class CommentHelper(PRAWBase):
    subreddit: Any = ...
    def __init__(self, subreddit: Any) -> None: ...
    def __call__(self, **generator_kwargs: Any): ...
    def gilded(self, **generator_kwargs: Any): ...
