# Stubs for praw.models.listing.domain (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ...const import API_PATH
from .mixins import BaseListingMixin, RisingListingMixin
from typing import Any

class DomainListing(BaseListingMixin, RisingListingMixin):
    def __init__(self, reddit: Any, domain: Any) -> None: ...
