from ...reddit import Reddit
from ..base import PRAWBase
from ..reddit.base import RedditBase
from .listing import FlairListing
from typing import Any, Optional, Iterator, TypeVar, Dict, TYPE_CHECKING

_T = TypeVar('_T', bound=RedditBase)

class ListingGenerator(PRAWBase, Iterator[_T]):
    limit: int = ...
    params: Dict[str, str] = ...
    url: str = ...
    yielded: int = ...

    def __init__(self, reddit: Reddit,
                       url: str,
                       limit: int = ...,
                       params: Optional[Dict[str, str]] = ...,
                       ) -> None: ...
    def __iter__(self) -> ListingGenerator[_T]: ...
    def __next__(self) -> _T: ...
    def next(self) -> _T: ...
