# Stubs for praw.models.front (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..const import urljoin
from .listing.generator import ListingGenerator
from .listing.mixins import SubredditListingMixin
from typing import Any

class Front(SubredditListingMixin):
    def __init__(self, reddit: Any) -> None: ...
    def best(self, **generator_kwargs: Any): ...
