# Stubs for praw.models.modaction (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import PRAWBase
from typing import Any

class ModAction(PRAWBase):
    @property
    def mod(self): ...
    @mod.setter
    def mod(self, value: Any) -> None: ...
