# Stubs for praw.models.preferences (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ..const import API_PATH
from typing import Any

class Preferences:
    def __call__(self): ...
    def __init__(self, reddit: Any) -> None: ...
    def update(self, **preferences: Any): ...
