# Stubs for praw.models.trophy (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .base import PRAWBase
from typing import Any

class Trophy(PRAWBase):
    def __init__(self, reddit: Any, _data: Any) -> None: ...
