from .exceptions import APIException
from .reddit import Reddit
from .models.reddit.base import RedditBase
from typing import Any, Optional, Dict, Type

class Objector:
    parsers: Dict[object, Type[RedditBase]] = ...
    def __init__(self, reddit: Reddit) -> None: ...
    def kind(self, instance: RedditBase) -> Any: ...
    def objectify(self, data: object) -> Optional[RedditBase]: ...
    def register(self, kind: object, cls: Type[RedditBase]) -> None: ...
