# Stubs for praw.models.reddit.mixins.replyable (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ....const import API_PATH
from ..comment import Comment
from typing import Any

class ReplyableMixin:
    def reply(self, body: str) -> Comment: ...
